[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
once_cell = "1.17"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["native-tls-vendored", "json"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "sqlite","migrate", "uuid", "chrono"] }
thiserror = "1.0"
bridge_macro = { path = "../bridge_macro" }
cfg-if = "1.0"
uuid = { version = "1.1.2", features = ["v4"] }
openmls = "0.4.1"
openmls_rust_crypto = "0.1.0"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"

[lib]
crate-type = ["staticlib", "cdylib"]
