[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
once_cell = "1.17"
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json"] }