[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
bridge_macro = { path = "../bridge_macro" }
tokio = { version = "1", features = ["full"] }
once_cell = "1.17"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["native-tls-vendored", "json"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "sqlite","migrate", "uuid", "chrono"] }
thiserror = "1.0"
uuid = { version = "1.3", features = ["v4"] }
openmls = "0.5.0-pre.3"
openmls_traits = "0.2.0-pre.1"
openmls_rust_crypto = "0.2.0-pre.1"
openmls_basic_credential = "0.2.0-pre.1"
rand_core = { version = "0.5.1" }
ed25519-dalek = "1.0.1"
serde_json = "1.0"
cfg-if = "1.0"
tls_codec = "0.3.0-pre.4"
sha2 = "0.10"
log = "0.4"

[dev-dependencies]
reqwest = { version = "0.11", features = ["native-tls-vendored", "json", "blocking"] }
simple_logger = "4.2"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"

[target.'cfg(target_os = "ios")'.dependencies]
oslog = "0.2"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]


[features]
default = ["development"]
development = []
staging = []
