[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
once_cell = "1.17"
serde = "1.0.137"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["native-tls-vendored", "json"] }
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "sqlite","migrate", "uuid", "chrono"] }
thiserror = "1.0"
bridge_macro = { path = "../bridge_macro" }
cfg-if = "1.0"
uuid = { version = "1.1.2", features = ["v4"] }
openmls = "0.4.1"
openmls_rust_crypto = "0.1.0"
ed25519-dalek = "1.0.1"
rand_core = "0.6.3"
rand_core_2 = { package = "rand_core", version = "0.5.1" }
common = { path = "../common" }
base64 = "0.21.0"
argon2 = "0.4.1"
serde_json = "1.0.82"

[dev-dependencies]
axum-test-helper = "0.1.0"
openmls_rust_crypto="0.1.0"
rand_core_2 = { package = "rand_core", version = "0.5.1" }


[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"

[lib]
crate-type = ["staticlib", "cdylib"]
