DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS location CASCADE;
DROP TABLE IF EXISTS "group" CASCADE;
DROP TABLE IF EXISTS location_group CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS attachment CASCADE;
DROP TABLE IF EXISTS user_group CASCADE;
DROP TABLE IF EXISTS message CASCADE;

