[package]
name = "bubble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "postgres", "migrate", "uuid"] }
tokio = { version = "1.18", features = ["full"] }
serde = "1.0.137"
once_cell ="1.12.0"

# Web framework
axum = "0.5.10"

# Random number generator
rand_core = "0.6.3"

[dependencies.uuid]
features = ["v4"]