[package]
name = "life180"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version ="0.5", features = ["runtime-tokio-rustls", "postgres", "migrate"] }
tokio = { version = "1.18", features = ["full"] }
axum = "0.5.7"