[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "sqlite", "postgres", "migrate", "uuid", "chrono"] }
tokio = { version = "1.18", features = ["full"] }
serde = "1.0.137"
once_cell = "1.12.0"
uuid = { version = "1.1.2", features = ["v4"] }
ed25519-dalek = "1.0.1"
axum = { version = "0.5.10", features = ["headers"] }
rand_core = "0.6.3"
argon2 = "0.4.1"
openmls = "0.4.1"
base64 = "0.21.0"
common = { path = "../common" }

# SendGrid
sendgrid = "0.19.0"



[dev-dependencies]
serde_json = "1.0.82"
axum-test-helper = "0.1.0"
openmls_rust_crypto="0.1.0"
rand_core_2 = { package = "rand_core", version = "0.5.1" }