[package]
name = "life180"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version ="0.5", features = ["runtime-tokio-rustls", "postgres", "migrate"] }
tokio = { version = "1.18", features = ["full"] }

# Web framework
axum = "0.5.7"

# Modular components for clients and servers
tower = "0.4.12"

# Deserialization and serialization framework
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

# HTTP Library
hyper = { version = "0.14.17", features = ["full"] }