[package]
name = "bubble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "postgres", "migrate", "uuid", "chrono"] }
tokio = { version = "1.18", features = ["full"] }
serde = "1.0.137"
once_cell ="1.12.0"

# Web framework
axum = {version = "0.5.10", features =["headers"]}

# Random number generator
rand_core = "0.6.3"

# Password Hashing
argon2 = "0.4.1"

[dependencies.uuid]
features = ["v4"]

[dev-dependencies]
axum-test-helper= "0.1.0"
serde_json = "1.0.82"