version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  migrate:
    build:
      context: .
      dockerfile: Dockerfile_migrate
    environment:
        DATABASE_URL: postgres://user:pass@postgres:5432/db
    depends_on:
      - postgres
