version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5433:5432"
  migrate:
    build: db
    command:
      - migrate
    environment:
        DATABASE_URL: postgres://user:pass@postgres:5432/db
    depends_on:
      - postgres
  server:
    build: server
    ports:
      - "${PORT}:3000"
    environment:
      DB_URL: postgres://user:pass@postgres:5432/db
      LISTEN_ADDR: "0.0.0.0:3000"
    depends_on:
      - postgres
      - migrate
