name: Database Tests
on:
  push:
    branches:
      - master
      - "feature/*"
    paths-ignore:
      - README.md

defaults:
  run:
    working-directory: packages/rust

jobs:
  migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make test_db_ci