name: JavaScript Tests

on:
  push:
    branches:
      - master
      - "feature/*"
    paths_ignore:
      - README.MD
defaults:
  run:
    working-directory: packages/js
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "19"
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build:ci

  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: "19"
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn lint:check