name: Rust Tests
on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    branches:
      - master
      - "feature/*"
    paths-ignore:
      - README.md

defaults:
  run:
    working-directory: packages/rust

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true
          profile: minimal
      - uses: actions-rs/install@v0.1
        with:
            crate: sleek
            version: latest
            use-tool-cache: true
      - run: make fmt_ci
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - run: make test_server_ci
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - run: cd frontend && make android-docker
