name: Rust Tests
on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    branches:
      - master
      - "feature/*"
    paths-ignore:
      - README.md

defaults:
  run:
    working-directory: packages/rust

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true
          profile: minimal
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - run: docker compose -f docker-compose-ci.yml up -d
      - run: docker run --rm --network="host" -e DATABASE_URL=postgres://user:pass@localhost:5433/db db migrate
        working-directory: packages/rust
      - run: cargo test --tests
        env:
          DB_URL: postgres://user:pass@localhost:5433/db
